# Filepaths
filepath:
  source_data: home-credit-default-risk/application_train.csv  # Relative to project root
  source_data_cc: home-credit-default-risk/credit_card_balance.csv
  model_sink: ../artifacts/model_classifier.pkl
  model_artifact_dir: mlartifacts/
  preprocessor_sink: ../artifacts/preprocessor.pkl  # Add this

# experiment name for mlflow
experiment_name: homecredit-default-11102025-v3
tuning_experiment_name: "hyperparameter_tuning_v1" 


# Model hyperparameters
model:
  subsample: 0.9
  reg_lambda: 1.0
  reg_alpha: 1.0
  num_leaves: 15
  n_estimators: 300
  min_child_samples: 5
  max_depth: 9
  learning_rate: 0.05
  colsample_bytree: 0.8

# Data split
train:
  test_size: 0.20
  random_state: 101
  use_cv: true        
  cv_folds: 5    

tuning:
  model_type: "lightgbm"  # or "xgboost"
  n_iter: 20                   # Number of random combinations to try
  cv_folds: 5                  # Cross-validation folds for tuning
  scoring: "f1"          # Metric to optimize    

# Features
features:
  numeric:
    - AMT_ANNUITY
    - AMT_INCOME_TOTAL
    - AMT_CREDIT
    - AMT_GOODS_PRICE
    - YEARS_EMPLOYED
    - UTILIZATION
    - MAX_UTILIZATION
    - EXT_SOURCE_1
    - EXT_SOURCE_2
    - EXT_SOURCE_3
    - MOB
    - AMT_PRIN_BAL_PAY_AVG
    - MAX_INSTALL
  categorical:  
    - EMPLOYMENT_BKT
    - OCCUPATION_TYPE
    - NAME_EDUCATION_TYPE
    - FLAG_OWN_CAR
    - FLAG_OWN_REALTY
    - FLAG_MOBIL
    - FLAG_EMP_PHONE
    - FLAG_WORK_PHONE
    - FLAG_CONT_MOBILE
    - FLAG_PHONE
    - FLAG_EMAIL
    - REG_REGION_NOT_LIVE_REGION
    - REG_REGION_NOT_WORK_REGION
    - LIVE_REGION_NOT_WORK_REGION
    - REG_CITY_NOT_LIVE_CITY
    - REG_CITY_NOT_WORK_CITY
    - LIVE_CITY_NOT_WORK_CITY
    - MAX_DPD_IND
#    - MIN_PAY_IND
#    - MIN_PAY_2P5_IND
  ordinal:
    - CNT_CHILDREN
    - CNT_FAM_MEMBERS
    


  #flag:
    
  
