# Filepaths
filepath:
  source_data: home-credit-default-risk/application_train.csv  # Relative to project root
  source_data_cc: home-credit-default-risk/credit_card_balance.csv
  model_sink: ../artifacts/model_classifier.pkl
  preprocessor_sink: ../artifacts/preprocessor.pkl  # Add this

# experiment name for mlflow
experiment_name: homecredit-default-11102025-v3

# Model hyperparameters
model:
  n_estimators: 40
  max_depth: 10
  class_weight: balanced
  random_state: 42

# Data split
train:
  test_size: 0.2
  random_state: 101
  stratify: true  # Add this - important for imbalanced data

# Features
features:
  numeric:
    - AMT_ANNUITY
    - AMT_INCOME_TOTAL
    - AMT_CREDIT
    - AMT_GOODS_PRICE
    - YEARS_EMPLOYED
    - UTILIZATION
  categorical:  
    - EMPLOYMENT_BKT
    - OCCUPATION_TYPE
    - NAME_EDUCATION_TYPE